-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.teams (
  name text NOT NULL UNIQUE,
  description text,
  department text,
  team_lead_id uuid,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT fk_teams_lead FOREIGN KEY (team_lead_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text NOT NULL,
  phone text,
  avatar_url text,
  team_id uuid,
  last_login_at timestamp with time zone,
  role USER-DEFINED NOT NULL DEFAULT 'employee'::user_role,
  status USER-DEFINED NOT NULL DEFAULT 'active'::user_status,
  timezone text NOT NULL DEFAULT 'UTC'::text,
  preferred_language text NOT NULL DEFAULT 'en'::text CHECK (preferred_language = ANY (ARRAY['en'::text, 'ar'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.client_profiles (
  id uuid NOT NULL,
  company_name text NOT NULL,
  contact_person text NOT NULL,
  email text NOT NULL UNIQUE,
  phone text,
  whatsapp_number text UNIQUE,
  address text,
  notes text,
  contract_start_date date,
  contract_end_date date,
  is_archived boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT client_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT client_profiles_id_fkey FOREIGN KEY (id) REFERENCES public.profiles(id)
);
CREATE TABLE public.rooms (
  name text NOT NULL UNIQUE,
  capacity integer NOT NULL CHECK (capacity > 0),
  location text,
  facilities ARRAY,
  description text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hourly_cost numeric NOT NULL DEFAULT 0.00 CHECK (hourly_cost >= 0::numeric),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT rooms_pkey PRIMARY KEY (id)
);
CREATE TABLE public.events (
  title text NOT NULL,
  description text,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  location text,
  recurrence_pattern jsonb,
  client_id uuid,
  created_by uuid NOT NULL,
  meeting_notes text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type USER-DEFINED NOT NULL DEFAULT 'other'::event_type,
  is_recurring boolean NOT NULL DEFAULT false,
  status USER-DEFINED NOT NULL DEFAULT 'scheduled'::event_status,
  is_client_visible boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.client_profiles(id),
  CONSTRAINT events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.event_attendees (
  event_id uuid NOT NULL,
  profile_id uuid NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_confirmed boolean NOT NULL DEFAULT false,
  notification_sent boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT event_attendees_pkey PRIMARY KEY (id),
  CONSTRAINT event_attendees_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_attendees_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.event_attachments (
  event_id uuid NOT NULL,
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_type text NOT NULL,
  file_size bigint,
  uploaded_by uuid NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT event_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT event_attachments_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.room_bookings (
  room_id uuid NOT NULL,
  booked_by uuid NOT NULL,
  client_id uuid,
  event_id uuid,
  booking_date date NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  total_cost numeric,
  notes text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  status USER-DEFINED NOT NULL DEFAULT 'confirmed'::booking_status,
  crm_entry_created boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT room_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT room_bookings_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id),
  CONSTRAINT room_bookings_booked_by_fkey FOREIGN KEY (booked_by) REFERENCES public.profiles(id),
  CONSTRAINT room_bookings_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.client_profiles(id),
  CONSTRAINT room_bookings_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id)
);
CREATE TABLE public.tasks (
  board_id uuid,
  board_column_id uuid,
  title text NOT NULL,
  description text,
  client_id uuid,
  team_id uuid,
  parent_task_id uuid,
  created_by uuid NOT NULL,
  due_date timestamp with time zone,
  cost numeric,
  budget_notes text,
  template_name text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  status USER-DEFINED NOT NULL DEFAULT 'not_started'::task_status,
  priority USER-DEFINED NOT NULL DEFAULT 'medium'::task_priority,
  completion_percentage integer NOT NULL DEFAULT 0 CHECK (completion_percentage >= 0 AND completion_percentage <= 100),
  is_template boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.client_profiles(id),
  CONSTRAINT tasks_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT tasks_parent_task_id_fkey FOREIGN KEY (parent_task_id) REFERENCES public.tasks(id),
  CONSTRAINT tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT tasks_board_id_fkey FOREIGN KEY (board_id) REFERENCES public.task_boards(id),
  CONSTRAINT tasks_board_column_id_fkey FOREIGN KEY (board_column_id) REFERENCES public.task_board_columns(id)
);
CREATE TABLE public.task_assignees (
  task_id uuid NOT NULL,
  profile_id uuid NOT NULL,
  assigned_by uuid NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_lead boolean NOT NULL DEFAULT false,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT task_assignees_pkey PRIMARY KEY (id),
  CONSTRAINT task_assignees_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT task_assignees_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT task_assignees_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.task_mentions (
  task_id uuid NOT NULL,
  mentioned_profile_id uuid NOT NULL,
  mentioned_by uuid NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  notification_sent boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT task_mentions_pkey PRIMARY KEY (id),
  CONSTRAINT task_mentions_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT task_mentions_mentioned_profile_id_fkey FOREIGN KEY (mentioned_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT task_mentions_mentioned_by_fkey FOREIGN KEY (mentioned_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.task_approvals (
  task_id uuid NOT NULL UNIQUE,
  employee_done_at timestamp with time zone,
  employee_done_by uuid,
  client_reviewed_at timestamp with time zone,
  client_reviewed_by uuid,
  client_decision USER-DEFINED,
  client_rejection_reason text,
  admin_override_at timestamp with time zone,
  admin_override_by uuid,
  admin_override_reason text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT task_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT task_approvals_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT task_approvals_employee_done_by_fkey FOREIGN KEY (employee_done_by) REFERENCES public.profiles(id),
  CONSTRAINT task_approvals_client_reviewed_by_fkey FOREIGN KEY (client_reviewed_by) REFERENCES public.profiles(id),
  CONSTRAINT task_approvals_admin_override_by_fkey FOREIGN KEY (admin_override_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.task_comments (
  task_id uuid NOT NULL,
  author_id uuid NOT NULL,
  content text NOT NULL,
  parent_comment_id uuid,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_internal boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT task_comments_pkey PRIMARY KEY (id),
  CONSTRAINT task_comments_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT task_comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.profiles(id),
  CONSTRAINT task_comments_parent_comment_id_fkey FOREIGN KEY (parent_comment_id) REFERENCES public.task_comments(id)
);
CREATE TABLE public.task_attachments (
  task_id uuid NOT NULL,
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_type text NOT NULL,
  file_size_bytes bigint,
  uploaded_by uuid NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_client_visible boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT task_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT task_attachments_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT task_attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.task_audit_log (
  task_id uuid NOT NULL,
  actor_id uuid NOT NULL,
  action text NOT NULL,
  old_value jsonb,
  new_value jsonb,
  notes text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT task_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT task_audit_log_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT task_audit_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.expense_categories (
  name text NOT NULL UNIQUE,
  description text,
  monthly_budget_limit numeric,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT expense_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.penalty_types (
  name text NOT NULL UNIQUE,
  description text,
  default_amount numeric,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT penalty_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.crm_entries (
  client_id uuid NOT NULL,
  source_id uuid,
  title text NOT NULL,
  description text,
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  due_date date,
  paid_at timestamp with time zone,
  invoice_number text UNIQUE,
  notes text,
  created_by uuid NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_type USER-DEFINED NOT NULL DEFAULT 'manual'::crm_source_type,
  currency text NOT NULL DEFAULT 'USD'::text,
  status USER-DEFINED NOT NULL DEFAULT 'unpaid'::crm_entry_status,
  paid_amount numeric NOT NULL DEFAULT 0.00 CHECK (paid_amount >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_entries_pkey PRIMARY KEY (id),
  CONSTRAINT crm_entries_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.client_profiles(id),
  CONSTRAINT crm_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.crm_payments (
  crm_entry_id uuid NOT NULL,
  client_id uuid NOT NULL,
  amount_paid numeric NOT NULL CHECK (amount_paid > 0::numeric),
  payment_date date NOT NULL,
  payment_method USER-DEFINED,
  reference_number text,
  recorded_by uuid NOT NULL,
  notes text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_payments_pkey PRIMARY KEY (id),
  CONSTRAINT crm_payments_crm_entry_id_fkey FOREIGN KEY (crm_entry_id) REFERENCES public.crm_entries(id),
  CONSTRAINT crm_payments_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.client_profiles(id),
  CONSTRAINT crm_payments_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.expenses (
  expense_date date NOT NULL,
  category_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  description text NOT NULL,
  receipt_url text,
  payment_method USER-DEFINED,
  paid_to text,
  recorded_by uuid NOT NULL,
  approved_by uuid,
  notes text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_recurring boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT expenses_pkey PRIMARY KEY (id),
  CONSTRAINT expenses_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.expense_categories(id),
  CONSTRAINT expenses_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.profiles(id),
  CONSTRAINT expenses_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.penalties (
  employee_id uuid NOT NULL,
  penalty_type_id uuid NOT NULL,
  penalty_date date NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  reason text NOT NULL,
  approved_by uuid NOT NULL,
  applied_at timestamp with time zone,
  notes text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_applied boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT penalties_pkey PRIMARY KEY (id),
  CONSTRAINT penalties_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.profiles(id),
  CONSTRAINT penalties_penalty_type_id_fkey FOREIGN KEY (penalty_type_id) REFERENCES public.penalty_types(id),
  CONSTRAINT penalties_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.attendance (
  employee_id uuid NOT NULL,
  attendance_date date NOT NULL,
  check_in_time timestamp with time zone,
  check_out_time timestamp with time zone,
  check_in_location jsonb,
  total_hours numeric,
  override_reason text,
  overridden_by uuid,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  status USER-DEFINED NOT NULL DEFAULT 'present'::attendance_status,
  is_overridden boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT attendance_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.profiles(id),
  CONSTRAINT attendance_overridden_by_fkey FOREIGN KEY (overridden_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.ai_interactions (
  client_id uuid,
  whatsapp_number text NOT NULL,
  incoming_message text NOT NULL,
  context_data jsonb,
  ai_response text,
  action_taken text,
  action_reference_id uuid,
  action_reference_type text,
  escalated_to uuid,
  n8n_execution_id text,
  response_time_ms integer,
  model_used text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  detected_intent USER-DEFINED DEFAULT 'unknown'::ai_intent,
  was_escalated boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT ai_interactions_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.client_profiles(id),
  CONSTRAINT ai_interactions_escalated_to_fkey FOREIGN KEY (escalated_to) REFERENCES public.profiles(id)
);
CREATE TABLE public.notifications (
  recipient_id uuid NOT NULL,
  type USER-DEFINED NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  reference_type text,
  reference_id uuid,
  read_at timestamp with time zone,
  sent_at timestamp with time zone,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_read boolean NOT NULL DEFAULT false,
  channel USER-DEFINED NOT NULL DEFAULT 'in_app'::notification_channel,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.task_boards (
  team_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  color text,
  icon text,
  created_by uuid NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_archived boolean NOT NULL DEFAULT false,
  position integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT task_boards_pkey PRIMARY KEY (id),
  CONSTRAINT task_boards_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT task_boards_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.task_board_columns (
  board_id uuid NOT NULL,
  name text NOT NULL,
  color text,
  maps_to_status USER-DEFINED,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  position integer NOT NULL DEFAULT 0,
  is_done_column boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT task_board_columns_pkey PRIMARY KEY (id),
  CONSTRAINT task_board_columns_board_id_fkey FOREIGN KEY (board_id) REFERENCES public.task_boards(id)
);
CREATE TABLE public.custom_tables (
  name text NOT NULL,
  description text,
  icon text,
  color text,
  team_id uuid,
  client_id uuid,
  created_by uuid NOT NULL,
  linked_task_board_id uuid,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_archived boolean NOT NULL DEFAULT false,
  position integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT custom_tables_pkey PRIMARY KEY (id),
  CONSTRAINT custom_tables_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT custom_tables_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.client_profiles(id),
  CONSTRAINT custom_tables_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT custom_tables_linked_task_board_id_fkey FOREIGN KEY (linked_task_board_id) REFERENCES public.task_boards(id)
);
CREATE TABLE public.custom_columns (
  table_id uuid NOT NULL,
  name text NOT NULL,
  field_type USER-DEFINED NOT NULL,
  created_by uuid NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  position integer NOT NULL DEFAULT 0,
  is_required boolean NOT NULL DEFAULT false,
  is_admin_only boolean NOT NULL DEFAULT false,
  is_hidden_from_client boolean NOT NULL DEFAULT false,
  is_hidden_from_employee boolean NOT NULL DEFAULT false,
  width integer NOT NULL DEFAULT 200,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT custom_columns_pkey PRIMARY KEY (id),
  CONSTRAINT custom_columns_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.custom_tables(id),
  CONSTRAINT custom_columns_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.column_status_options (
  column_id uuid NOT NULL,
  label text NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  color text NOT NULL DEFAULT '#888888'::text,
  position integer NOT NULL DEFAULT 0,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT column_status_options_pkey PRIMARY KEY (id),
  CONSTRAINT column_status_options_column_id_fkey FOREIGN KEY (column_id) REFERENCES public.custom_columns(id)
);
CREATE TABLE public.custom_rows (
  table_id uuid NOT NULL,
  created_by uuid NOT NULL,
  linked_task_id uuid,
  linked_client_id uuid,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  position integer NOT NULL DEFAULT 0,
  is_archived boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT custom_rows_pkey PRIMARY KEY (id),
  CONSTRAINT custom_rows_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.custom_tables(id),
  CONSTRAINT custom_rows_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT custom_rows_linked_task_id_fkey FOREIGN KEY (linked_task_id) REFERENCES public.tasks(id),
  CONSTRAINT custom_rows_linked_client_id_fkey FOREIGN KEY (linked_client_id) REFERENCES public.client_profiles(id)
);
CREATE TABLE public.custom_cell_values (
  row_id uuid NOT NULL,
  column_id uuid NOT NULL,
  value_text text,
  value_number numeric,
  value_date timestamp with time zone,
  value_date_end timestamp with time zone,
  value_boolean boolean,
  value_jsonb jsonb,
  last_edited_by uuid,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT custom_cell_values_pkey PRIMARY KEY (id),
  CONSTRAINT custom_cell_values_row_id_fkey FOREIGN KEY (row_id) REFERENCES public.custom_rows(id),
  CONSTRAINT custom_cell_values_column_id_fkey FOREIGN KEY (column_id) REFERENCES public.custom_columns(id),
  CONSTRAINT custom_cell_values_last_edited_by_fkey FOREIGN KEY (last_edited_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.table_views (
  table_id uuid NOT NULL,
  name text NOT NULL,
  created_by uuid NOT NULL,
  group_by_column_id uuid,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  view_type USER-DEFINED NOT NULL DEFAULT 'list'::view_type,
  is_default boolean NOT NULL DEFAULT false,
  sort_config jsonb NOT NULL DEFAULT '[]'::jsonb,
  filter_config jsonb NOT NULL DEFAULT '[]'::jsonb,
  hidden_column_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  column_order ARRAY NOT NULL DEFAULT '{}'::uuid[],
  column_widths jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT table_views_pkey PRIMARY KEY (id),
  CONSTRAINT table_views_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.custom_tables(id),
  CONSTRAINT table_views_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT table_views_group_by_column_id_fkey FOREIGN KEY (group_by_column_id) REFERENCES public.custom_columns(id)
);
CREATE TABLE public.table_permissions (
  table_id uuid NOT NULL,
  grantee_type USER-DEFINED NOT NULL,
  grantee_id uuid NOT NULL,
  granted_by uuid NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  can_view boolean NOT NULL DEFAULT true,
  can_add_rows boolean NOT NULL DEFAULT false,
  can_edit_rows boolean NOT NULL DEFAULT false,
  can_delete_rows boolean NOT NULL DEFAULT false,
  can_manage_columns boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT table_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT table_permissions_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.custom_tables(id),
  CONSTRAINT table_permissions_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.cell_audit_log (
  cell_id uuid NOT NULL,
  row_id uuid NOT NULL,
  column_id uuid NOT NULL,
  actor_id uuid NOT NULL,
  old_value jsonb,
  new_value jsonb,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cell_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT cell_audit_log_cell_id_fkey FOREIGN KEY (cell_id) REFERENCES public.custom_cell_values(id),
  CONSTRAINT cell_audit_log_row_id_fkey FOREIGN KEY (row_id) REFERENCES public.custom_rows(id),
  CONSTRAINT cell_audit_log_column_id_fkey FOREIGN KEY (column_id) REFERENCES public.custom_columns(id),
  CONSTRAINT cell_audit_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.note_tags (
  name text NOT NULL,
  created_by uuid NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  color text NOT NULL DEFAULT '#888888'::text,
  is_global boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT note_tags_pkey PRIMARY KEY (id),
  CONSTRAINT note_tags_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.notes (
  owner_id uuid NOT NULL,
  color text,
  archived_at timestamp with time zone,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL DEFAULT 'Untitled'::text,
  content jsonb NOT NULL DEFAULT '{"type": "doc", "content": []}'::jsonb,
  visibility USER-DEFINED NOT NULL DEFAULT 'private'::note_visibility,
  is_pinned boolean NOT NULL DEFAULT false,
  tag_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  is_archived boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notes_pkey PRIMARY KEY (id),
  CONSTRAINT notes_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.note_shares (
  note_id uuid NOT NULL,
  shared_with uuid NOT NULL,
  shared_by uuid NOT NULL,
  message text,
  expires_at timestamp with time zone,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  permission USER-DEFINED NOT NULL DEFAULT 'view'::share_permission,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT note_shares_pkey PRIMARY KEY (id),
  CONSTRAINT note_shares_note_id_fkey FOREIGN KEY (note_id) REFERENCES public.notes(id),
  CONSTRAINT note_shares_shared_with_fkey FOREIGN KEY (shared_with) REFERENCES public.profiles(id),
  CONSTRAINT note_shares_shared_by_fkey FOREIGN KEY (shared_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.note_attachments (
  note_id uuid NOT NULL,
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_type text NOT NULL,
  file_size_bytes bigint,
  uploaded_by uuid NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_image boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT note_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT note_attachments_note_id_fkey FOREIGN KEY (note_id) REFERENCES public.notes(id),
  CONSTRAINT note_attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.note_links (
  note_id uuid NOT NULL,
  link_type USER-DEFINED NOT NULL,
  linked_id uuid NOT NULL,
  display_label text,
  linked_by uuid NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT note_links_pkey PRIMARY KEY (id),
  CONSTRAINT note_links_note_id_fkey FOREIGN KEY (note_id) REFERENCES public.notes(id),
  CONSTRAINT note_links_linked_by_fkey FOREIGN KEY (linked_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.note_audit_log (
  note_id uuid NOT NULL,
  actor_id uuid NOT NULL,
  action text NOT NULL,
  old_title text,
  new_title text,
  old_content jsonb,
  new_content jsonb,
  meta jsonb,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT note_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT note_audit_log_note_id_fkey FOREIGN KEY (note_id) REFERENCES public.notes(id),
  CONSTRAINT note_audit_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.client_task_visibility (
  team_id uuid NOT NULL,
  client_id uuid NOT NULL,
  configured_by uuid NOT NULL,
  notes text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  can_see_tasks_section boolean NOT NULL DEFAULT true,
  can_see_completed_tasks boolean NOT NULL DEFAULT true,
  can_see_cancelled_tasks boolean NOT NULL DEFAULT false,
  can_see_task_comments boolean NOT NULL DEFAULT true,
  can_see_task_files boolean NOT NULL DEFAULT true,
  can_approve_tasks boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT client_task_visibility_pkey PRIMARY KEY (id),
  CONSTRAINT client_task_visibility_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT client_task_visibility_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.client_profiles(id),
  CONSTRAINT client_task_visibility_configured_by_fkey FOREIGN KEY (configured_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.client_task_column_visibility (
  team_id uuid NOT NULL,
  client_id uuid NOT NULL,
  column_key USER-DEFINED NOT NULL,
  configured_by uuid NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_visible boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT client_task_column_visibility_pkey PRIMARY KEY (id),
  CONSTRAINT client_task_column_visibility_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT client_task_column_visibility_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.client_profiles(id),
  CONSTRAINT client_task_column_visibility_configured_by_fkey FOREIGN KEY (configured_by) REFERENCES public.profiles(id)
);

-- Enable Supabase Realtime for notifications table
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;